public class Airth1 {
        integer a = 20;
        integer b= 10;
    public void doAdd(){
        integer c = a + b;
        System.debug('Result ='+c);
    }
    public void doSub(){
        integer c = a - b;
        System.debug('Result = '+c);
    }
    public void doDiv(){
        integer c = a / b;
        System.debug('Result ='+c);
    }
    public void doMul(){
        integer c = a * b;
        System.debug('Result ='+c);
    }

}